<li class="hobby-section" data-bind="scope: 'hobbySection'">
    <!-- ko if: hobbySection().hobby -->
    <span data-bind="text: new String('<?= $escaper->escapeHtml(__('Hobby: %1!', '%1')) ?>').replace('%1', hobbySection().hobby)">
        </span>
    <!-- /ko -->
</li>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "hobbySection": {
                        "component": "Test_Hobby/js/section"
                    }
                }
            }
        }
    }
</script>